/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as WachtwoordHerstellenRouteImport } from './routes/wachtwoord-herstellen'
import { Route as WachtwoordVergetenRouteImport } from './routes/wachtwoord-vergeten'
import { Route as AuthenticatedBeheerRouteImport } from './routes/_authenticated/beheer'
import { Route as AuthenticatedBijnaVerlopenRouteImport } from './routes/_authenticated/bijna-verlopen'
import { Route as AuthenticatedBoodschappenRouteImport } from './routes/_authenticated/boodschappen'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGeopendRouteImport } from './routes/_authenticated/geopend'
import { Route as AuthenticatedInvoerRouteImport } from './routes/_authenticated/invoer'
import { Route as AuthenticatedUitgifteRouteImport } from './routes/_authenticated/uitgifte'
import { Route as AuthenticatedVoorraadRouteImport } from './routes/_authenticated/voorraad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const WachtwoordHerstellenRoute = WachtwoordHerstellenRouteImport.update({
  id: '/wachtwoord-herstellen',
  path: '/wachtwoord-herstellen',
  getParentRoute: () => rootRouteImport,
} as any)
const WachtwoordVergetenRoute = WachtwoordVergetenRouteImport.update({
  id: '/wachtwoord-vergeten',
  path: '/wachtwoord-vergeten',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBeheerRoute = AuthenticatedBeheerRouteImport.update({
  id: '/beheer',
  path: '/beheer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBijnaVerlopenRoute =
  AuthenticatedBijnaVerlopenRouteImport.update({
    id: '/bijna-verlopen',
    path: '/bijna-verlopen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoodschappenRoute =
  AuthenticatedBoodschappenRouteImport.update({
    id: '/boodschappen',
    path: '/boodschappen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeopendRoute = AuthenticatedGeopendRouteImport.update({
  id: '/geopend',
  path: '/geopend',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoerRoute = AuthenticatedInvoerRouteImport.update({
  id: '/invoer',
  path: '/invoer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUitgifteRoute = AuthenticatedUitgifteRouteImport.update({
  id: '/uitgifte',
  path: '/uitgifte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoorraadRoute = AuthenticatedVoorraadRouteImport.update({
  id: '/voorraad',
  path: '/voorraad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wachtwoord-herstellen': typeof WachtwoordHerstellenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/beheer': typeof AuthenticatedBeheerRoute
  '/bijna-verlopen': typeof AuthenticatedBijnaVerlopenRoute
  '/boodschappen': typeof AuthenticatedBoodschappenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/geopend': typeof AuthenticatedGeopendRoute
  '/invoer': typeof AuthenticatedInvoerRoute
  '/uitgifte': typeof AuthenticatedUitgifteRoute
  '/voorraad': typeof AuthenticatedVoorraadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wachtwoord-herstellen': typeof WachtwoordHerstellenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/beheer': typeof AuthenticatedBeheerRoute
  '/bijna-verlopen': typeof AuthenticatedBijnaVerlopenRoute
  '/boodschappen': typeof AuthenticatedBoodschappenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/geopend': typeof AuthenticatedGeopendRoute
  '/invoer': typeof AuthenticatedInvoerRoute
  '/uitgifte': typeof AuthenticatedUitgifteRoute
  '/voorraad': typeof AuthenticatedVoorraadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/wachtwoord-herstellen': typeof WachtwoordHerstellenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/_authenticated/beheer': typeof AuthenticatedBeheerRoute
  '/_authenticated/bijna-verlopen': typeof AuthenticatedBijnaVerlopenRoute
  '/_authenticated/boodschappen': typeof AuthenticatedBoodschappenRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/geopend': typeof AuthenticatedGeopendRoute
  '/_authenticated/invoer': typeof AuthenticatedInvoerRoute
  '/_authenticated/uitgifte': typeof AuthenticatedUitgifteRoute
  '/_authenticated/voorraad': typeof AuthenticatedVoorraadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wachtwoord-herstellen'
    | '/wachtwoord-vergeten'
    | '/beheer'
    | '/bijna-verlopen'
    | '/boodschappen'
    | '/dashboard'
    | '/geopend'
    | '/invoer'
    | '/uitgifte'
    | '/voorraad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/wachtwoord-herstellen'
    | '/wachtwoord-vergeten'
    | '/beheer'
    | '/bijna-verlopen'
    | '/boodschappen'
    | '/dashboard'
    | '/geopend'
    | '/invoer'
    | '/uitgifte'
    | '/voorraad'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/wachtwoord-herstellen'
    | '/wachtwoord-vergeten'
    | '/_authenticated/beheer'
    | '/_authenticated/bijna-verlopen'
    | '/_authenticated/boodschappen'
    | '/_authenticated/dashboard'
    | '/_authenticated/geopend'
    | '/_authenticated/invoer'
    | '/_authenticated/uitgifte'
    | '/_authenticated/voorraad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  WachtwoordHerstellenRoute: typeof WachtwoordHerstellenRoute
  WachtwoordVergetenRoute: typeof WachtwoordVergetenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wachtwoord-herstellen': {
      id: '/wachtwoord-herstellen'
      path: '/wachtwoord-herstellen'
      fullPath: '/wachtwoord-herstellen'
      preLoaderRoute: typeof WachtwoordHerstellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wachtwoord-vergeten': {
      id: '/wachtwoord-vergeten'
      path: '/wachtwoord-vergeten'
      fullPath: '/wachtwoord-vergeten'
      preLoaderRoute: typeof WachtwoordVergetenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/beheer': {
      id: '/_authenticated/beheer'
      path: '/beheer'
      fullPath: '/beheer'
      preLoaderRoute: typeof AuthenticatedBeheerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bijna-verlopen': {
      id: '/_authenticated/bijna-verlopen'
      path: '/bijna-verlopen'
      fullPath: '/bijna-verlopen'
      preLoaderRoute: typeof AuthenticatedBijnaVerlopenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boodschappen': {
      id: '/_authenticated/boodschappen'
      path: '/boodschappen'
      fullPath: '/boodschappen'
      preLoaderRoute: typeof AuthenticatedBoodschappenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/geopend': {
      id: '/_authenticated/geopend'
      path: '/geopend'
      fullPath: '/geopend'
      preLoaderRoute: typeof AuthenticatedGeopendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoer': {
      id: '/_authenticated/invoer'
      path: '/invoer'
      fullPath: '/invoer'
      preLoaderRoute: typeof AuthenticatedInvoerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/uitgifte': {
      id: '/_authenticated/uitgifte'
      path: '/uitgifte'
      fullPath: '/uitgifte'
      preLoaderRoute: typeof AuthenticatedUitgifteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voorraad': {
      id: '/_authenticated/voorraad'
      path: '/voorraad'
      fullPath: '/voorraad'
      preLoaderRoute: typeof AuthenticatedVoorraadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBeheerRoute: typeof AuthenticatedBeheerRoute
  AuthenticatedBijnaVerlopenRoute: typeof AuthenticatedBijnaVerlopenRoute
  AuthenticatedBoodschappenRoute: typeof AuthenticatedBoodschappenRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGeopendRoute: typeof AuthenticatedGeopendRoute
  AuthenticatedInvoerRoute: typeof AuthenticatedInvoerRoute
  AuthenticatedUitgifteRoute: typeof AuthenticatedUitgifteRoute
  AuthenticatedVoorraadRoute: typeof AuthenticatedVoorraadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBeheerRoute: AuthenticatedBeheerRoute,
  AuthenticatedBijnaVerlopenRoute: AuthenticatedBijnaVerlopenRoute,
  AuthenticatedBoodschappenRoute: AuthenticatedBoodschappenRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGeopendRoute: AuthenticatedGeopendRoute,
  AuthenticatedInvoerRoute: AuthenticatedInvoerRoute,
  AuthenticatedUitgifteRoute: AuthenticatedUitgifteRoute,
  AuthenticatedVoorraadRoute: AuthenticatedVoorraadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  WachtwoordHerstellenRoute: WachtwoordHerstellenRoute,
  WachtwoordVergetenRoute: WachtwoordVergetenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
