/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as WachtwoordHerstellenRouteImport } from './routes/wachtwoord-herstellen'
import { Route as WachtwoordVergetenRouteImport } from './routes/wachtwoord-vergeten'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInvoerRouteImport } from './routes/_authenticated/invoer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const WachtwoordHerstellenRoute = WachtwoordHerstellenRouteImport.update({
  id: '/wachtwoord-herstellen',
  path: '/wachtwoord-herstellen',
  getParentRoute: () => rootRouteImport,
} as any)
const WachtwoordVergetenRoute = WachtwoordVergetenRouteImport.update({
  id: '/wachtwoord-vergeten',
  path: '/wachtwoord-vergeten',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoerRoute = AuthenticatedInvoerRouteImport.update({
  id: '/invoer',
  path: '/invoer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wachtwoord-herstellen': typeof WachtwoordHerstellenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoer': typeof AuthenticatedInvoerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wachtwoord-herstellen': typeof WachtwoordHerstellenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoer': typeof AuthenticatedInvoerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/wachtwoord-herstellen': typeof WachtwoordHerstellenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoer': typeof AuthenticatedInvoerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wachtwoord-herstellen'
    | '/wachtwoord-vergeten'
    | '/dashboard'
    | '/invoer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/wachtwoord-herstellen'
    | '/wachtwoord-vergeten'
    | '/dashboard'
    | '/invoer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/wachtwoord-herstellen'
    | '/wachtwoord-vergeten'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  WachtwoordHerstellenRoute: typeof WachtwoordHerstellenRoute
  WachtwoordVergetenRoute: typeof WachtwoordVergetenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wachtwoord-herstellen': {
      id: '/wachtwoord-herstellen'
      path: '/wachtwoord-herstellen'
      fullPath: '/wachtwoord-herstellen'
      preLoaderRoute: typeof WachtwoordHerstellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wachtwoord-vergeten': {
      id: '/wachtwoord-vergeten'
      path: '/wachtwoord-vergeten'
      fullPath: '/wachtwoord-vergeten'
      preLoaderRoute: typeof WachtwoordVergetenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoer': {
      id: '/_authenticated/invoer'
      path: '/invoer'
      fullPath: '/invoer'
      preLoaderRoute: typeof AuthenticatedInvoerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoerRoute: typeof AuthenticatedInvoerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoerRoute: AuthenticatedInvoerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  WachtwoordHerstellenRoute: WachtwoordHerstellenRoute,
  WachtwoordVergetenRoute: WachtwoordVergetenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
